import { useEffect, useState } from 'react';
import { Alert, AppBar, Box, Button, Card, CardActions, CardContent, CardMedia, Chip, Container, Dialog, DialogActions, DialogContent, DialogTitle, Grid, IconButton, Stack, TextField, Toolbar, Typography } from '@mui/material';
import { AddShoppingCart, ArrowBack, DeleteOutline, ShoppingBag } from '@mui/icons-material';
import { commerceAPI, productAPI } from './api/client';

export default function App() {
  const [health, setHealth] = useState(null);
  const [error, setError] = useState('');
  const [products, setProducts] = useState([]); const [cart, setCart] = useState({ items: [], total: 0 }); const [orders, setOrders] = useState([]);
  const [query, setQuery] = useState(''); const [page, setPage] = useState('shop'); const [selected, setSelected] = useState(null); const [payment, setPayment] = useState(null); const [message, setMessage] = useState('');
  const refresh = () => commerceAPI.cart().then(({ data }) => setCart(data));
  useEffect(() => { productAPI.list().then(({ data }) => setProducts(data)).catch(() => setMessage('Backend is not reachable.')); refresh(); }, []);
  const search = (event) => { event.preventDefault(); productAPI.list({ q: query }).then(({ data }) => setProducts(data)); };
  const add = (id) => commerceAPI.add(id).then(({ data }) => { setCart(data); setMessage('Added to cart.'); });
  const checkout = () => commerceAPI.checkout().then(({ data }) => { setPayment(data); setPage('payment'); }).catch((e) => setMessage(e.response?.data?.error || 'Checkout failed.'));
  const loadOrders = () => commerceAPI.orders().then(({ data }) => { setOrders(data); setPage('orders'); });
  const pay = (result) => commerceAPI.pay(payment.orderId, result).then(({ data }) => { setPayment(data); loadOrders(); }).catch((e) => setMessage(e.response?.data?.error || 'Payment failed.'));
  return <Box sx={{ minHeight: '100vh', bgcolor: '#f7f5ef' }}><AppBar position="static" sx={{ bgcolor: '#193b36' }}><Toolbar><Typography variant="h5" sx={{ flexGrow: 1, fontWeight: 800, letterSpacing: -1 }}>loom / market</Typography><Button color="inherit" onClick={() => setPage('shop')}>Shop</Button><Button color="inherit" onClick={() => loadOrders()}>Orders</Button><Button color="inherit" startIcon={<ShoppingBag />} onClick={() => setPage('cart')}>Cart ({cart.items.length})</Button></Toolbar></AppBar>
    <Container maxWidth="lg" sx={{ py: 5 }}>{message && <Alert onClose={() => setMessage('')} sx={{ mb: 3 }} severity="info">{message}</Alert>}{page === 'shop' && <Shop products={products} query={query} setQuery={setQuery} search={search} add={add} open={(p) => { setSelected(p); setPage('detail'); }} />}{page === 'detail' && <Detail product={selected} back={() => setPage('shop')} add={add} />}{page === 'cart' && <Cart cart={cart} remove={(id) => commerceAPI.remove(id).then(({ data }) => setCart(data))} checkout={checkout} />}{page === 'payment' && <Payment payment={payment} pay={pay} />}{page === 'orders' && <Orders orders={orders} open={(o) => commerceAPI.order(o.id).then(({ data }) => { setSelected(data); setPage('order'); })} />}{page === 'order' && <Order order={selected} back={() => setPage('orders')} />}</Container></Box>;
}
function Shop({ products, query, setQuery, search, add, open }) { return <><Box sx={{ mb: 5 }}><Typography variant="overline" color="secondary">Objects for focused living</Typography><Typography variant="h2" sx={{ fontWeight: 800, maxWidth: 650, mb: 2 }}>Good tools make room for good work.</Typography><form onSubmit={search}><TextField value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search the collection" size="small" sx={{ width: 330, bgcolor: 'white' }} /><Button type="submit" variant="contained" sx={{ ml: 1, py: 1.5 }}>Search</Button></form></Box><Grid container spacing={3}>{products.map((p) => <Grid item xs={12} sm={6} md={4} key={p.id}><Card sx={{ height: '100%', cursor: 'pointer' }} onClick={() => open(p)}><CardMedia component="img" height="220" image={p.imageUrl} alt="" /><CardContent><Chip label={p.category} size="small" sx={{ mb: 1 }} /><Typography variant="h5" sx={{ fontWeight: 700 }}>{p.name}</Typography><Typography color="text.secondary" sx={{ my: 1 }}>{p.description}</Typography><Typography variant="h6">{money(p.price)}</Typography></CardContent><CardActions><Button startIcon={<AddShoppingCart />} onClick={(e) => { e.stopPropagation(); add(p.id); }}>Add to cart</Button><Typography variant="caption" sx={{ ml: 'auto', mr: 1 }}>{p.stock} available</Typography></CardActions></Card></Grid>)}</Grid></>; }
function Detail({ product, back, add }) { return <Stack spacing={3}><Button startIcon={<ArrowBack />} onClick={back} sx={{ alignSelf: 'flex-start' }}>Back to shop</Button><Grid container spacing={5}><Grid item xs={12} md={6}><Box component="img" src={product.imageUrl} alt="" sx={{ width: '100%', maxHeight: 500, objectFit: 'cover' }} /></Grid><Grid item xs={12} md={6}><Chip label={product.category} /><Typography variant="h2" sx={{ fontWeight: 800, my: 2 }}>{product.name}</Typography><Typography variant="h4" color="secondary">{money(product.price)}</Typography><Typography sx={{ my: 3 }}>{product.description}</Typography><Button variant="contained" startIcon={<AddShoppingCart />} onClick={() => add(product.id)}>Add to cart</Button></Grid></Grid></Stack>; }
function Cart({ cart, remove, checkout }) { return <><Typography variant="h3" sx={{ fontWeight: 800, mb: 3 }}>Your cart</Typography>{cart.items.length === 0 ? <Typography>Your cart is waiting for a good idea.</Typography> : <Stack spacing={2}>{cart.items.map((i) => <Card key={i.productId}><CardContent sx={{ display: 'flex', alignItems: 'center' }}><Box sx={{ flexGrow: 1 }}><Typography variant="h6">{i.name}</Typography><Typography color="text.secondary">{i.quantity} × {money(i.price)}</Typography></Box><Typography variant="h6">{money(i.quantity * i.price)}</Typography><IconButton onClick={() => remove(i.productId)}><DeleteOutline /></IconButton></CardContent></Card>)}<Typography variant="h5" sx={{ textAlign: 'right' }}>Total: {money(cart.total)}</Typography><Button variant="contained" onClick={checkout} sx={{ alignSelf: 'flex-end' }}>Reserve and checkout</Button></Stack>}</>; }
function Payment({ payment, pay }) { return <Stack spacing={3} maxWidth="sm"><Typography variant="h3" sx={{ fontWeight: 800 }}>Payment</Typography><Alert severity="info">Stock is reserved until {new Date(payment.reservationExpiresAt).toLocaleTimeString()}.</Alert><Typography variant="h5">Order #{payment.orderId} · {money(payment.total)}</Typography><Typography>Choose a mock gateway result:</Typography><Button variant="contained" onClick={() => pay('SUCCESS')}>Pay successfully</Button><Button color="error" onClick={() => pay('FAILURE')}>Simulate failure</Button><Button onClick={() => pay('TIMEOUT')}>Simulate timeout</Button></Stack>; }
function Orders({ orders, open }) { return <><Typography variant="h3" sx={{ fontWeight: 800, mb: 3 }}>Order history</Typography><Stack spacing={2}>{orders.map((o) => <Card key={o.id} onClick={() => open(o)} sx={{ cursor: 'pointer' }}><CardContent sx={{ display: 'flex' }}><Box sx={{ flexGrow: 1 }}><Typography variant="h6">Order #{o.id}</Typography><Typography color="text.secondary">{new Date(o.createdAt).toLocaleString()}</Typography></Box><Chip label={o.status} color={o.status === 'PAID' ? 'success' : 'default'} /><Typography sx={{ ml: 2, fontWeight: 700 }}>{money(o.total)}</Typography></CardContent></Card>)}</Stack></>; }
function Order({ order, back }) { return <Stack spacing={2}><Button startIcon={<ArrowBack />} onClick={back} sx={{ alignSelf: 'flex-start' }}>Back to orders</Button><Typography variant="h3" sx={{ fontWeight: 800 }}>Order #{order.id}</Typography><Typography>Status: {order.status} · Payment: {order.paymentStatus}</Typography>{order.items.map((i) => <Typography key={i.name}>{i.quantity} × {i.name} · {money(i.unitPrice)}</Typography>)}<Typography variant="h5">Total {money(order.total)}</Typography></Stack>; }
function money(value) { return `$${Number(value || 0).toFixed(2)}`; }
